### ISSUE TITLE
对tf.image.ssim使用存在一点疑问

### ISSUE THREAD

**Issue by IPNUISTlegal** [Zheng222/PPCN#1]
https://github.com/Zheng222/PPCN/blob/344bd67f6b1f295763d58c0d0af6c855a70980b3/SR_train/train_SR.py#L70
根据TensorFlow API https://www.tensorflow.org/api_docs/python/tf/image/ssim  
tensor_sr和tensor_hr都是'float32'类型数据，max_val应该是1.0而不是255，我有点不能理解，希望得到您的答复，谢谢

**Comment by Zheng222** [comment]
@IPNUISTlegal 你好，这里`max_val=255`是因为我的输入图和输出的取值范围是[0, 255.0]，数据类型是float32。

**Comment by Zheng222** [comment]
@IPNUISTlegal Hello, here, `max_val=255` is because my input and output images have a value range of [0, 255.0], and the data type is float32.

**Comment by IPNUISTlegal** [comment]
@Zheng222  那我可以这样理解吗？取值范围是[0, 255.0] 是没有经过归一化，max_val用255，经过归一化的， max_val用1.0？

**Comment by Zheng222** [comment]
@IPNUISTlegal 你好，简单来说，你的图像数据范围是多少，`max_val`就取多大。[0,1]和[0, 255]是两种比较常见的数值范围。

**Comment by IPNUISTlegal** [comment]
好的。谢谢，看来我要把归一化结果[-1,+1]加1再除以2，用max_val=1.0
